language: csharp
mono: none
dotnet: 2.1.403

install:
- dotnet restore

script:
 - dotnet build
 - dotnet test KanKanTest/KanKanTest.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
        - bash <(curl -s https://codecov.io/bash) 
